const slikeVozila2 = {
  "Alfa Romeo": "assets/icons_logo2/alfa-romeo.png",
  Audi: "assets/icons_logo2/audi.png",
  Bentley: "assets/icons_logo2/bentley.png",
  "Aston Martin": "assets/icons_logo2/aston-martin.png",
  BMW: "assets/icons_logo2/bmw.png",
  Bugatti: "assets/icons_logo2/bugatti.png",
  Chevrolet: "assets/icons_logo2/chevrolet.png",
  Citroen: "assets/icons_logo2/citroen.png",
  Dacia: "assets/icons_logo2/dacia.png",
  Daewoo: "assets/icons_logo2/daewoo.png",
  Dodge: "assets/icons_logo2/dodge.png",
  Ferrari: "assets/icons_logo2/ferrari.png",
  Fiat: "assets/icons_logo2/fiat.png",
  Ford: "assets/icons_logo2/ford.png",
  Honda: "assets/icons_logo2/honda.png",
  Hummer: "assets/icons_logo2/hummer.png",
  Hyundai: "assets/icons_logo2/hyundai.png",
  Infiniti: "assets/icons_logo2/infiniti.png",
  Jaguar: "assets/icons_logo2/jaguar.png",
  Jeep: "assets/icons_logo2/jeep.png",
  Kia: "assets/icons_logo2/kia.png",
  Lada: "assets/icons_logo2/lada.png",
  Lamborghini: "assets/icons_logo2/lamborghini.png",
  "Land Rover": "assets/icons_logo2/land-rover.png",
  Lexus: "assets/icons_logo2/lexus.png",
  Maserati: "assets/icons_logo2/maserati.png",
  Mazda: "assets/icons_logo2/mazda.png",
  McLaren: "assets/icons_logo2/mclaren.png",
  Mercedes: "assets/icons_logo2/mercedes-benz.png",
  MINI: "assets/icons_logo2/mini.png",
  Mitsubishi: "assets/icons_logo2/mitsubishi.png",
  Nissan: "assets/icons_logo2/nissan.png",
  Opel: "assets/icons_logo2/opel.png",
  Peugeot: "assets/icons_logo2/peugeot.png",
  Porsche: "assets/icons_logo2/porsche.png",
  Renault: "assets/icons_logo2/renault.png",
  "Rolls-Royce": "assets/icons_logo2/rolls-royce.png",
  Rover: "assets/icons_logo2/rover.png",
  Saab: "assets/icons_logo2/saab.png",
  Seat: "assets/icons_logo2/seat.png",
  Skoda: "assets/icons_logo2/skoda.png",
  Smart: "assets/icons_logo2/smart.png",
  Subaru: "assets/icons_logo2/subaru.png",
  Suzuki: "assets/icons_logo2/suzuki.png",
  Tesla: "assets/icons_logo2/tesla.png",
  Toyota: "assets/icons_logo2/toyota.png",
  Volkswagen: "assets/icons_logo2/volkswagen.png",
  Volvo: "assets/icons_logo2/volvo.png",
  Zastava: "assets/icons_logo2/zastava.png",
  default: "assets/icons_logo/default.svg",
};

export const getVehicleImage2 = (brand) =>
  slikeVozila2[brand] || slikeVozila2.default;
